# Generated by Django 4.1.6 on 2023-02-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLight',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('uptime', models.IntegerField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PolePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('power', models.DecimalField(decimal_places=2, max_digits=15)),
                ('streetLight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power', to='tracker.streetlight')),
            ],
        ),
    ]
