# Generated by Django 4.1.6 on 2023-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polepower',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='streetlight',
            name='uptime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
