# Generated by Django 4.1.6 on 2023-02-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_polepower_power_streetlight_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetlight',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='streetlight',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=4, null=True),
        ),
    ]
