# Generated by Django 4.1.6 on 2023-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_streetlight_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streetlight',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='streetlight',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
    ]
